from enum import StrEnum


class TaskState(StrEnum):
    CREATED = "CREATED"
    VALIDATED = "VALIDATED"
    QUOTED = "QUOTED"
    PROVISIONING = "PROVISIONING"
    PREPARING = "PREPARING"
    RUNNING = "RUNNING"
    UPLOADING = "UPLOADING"
    VERIFYING = "VERIFYING"
    TEARING_DOWN = "TEARING_DOWN"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    DEGRADED = "DEGRADED"
    FAILED_TEARDOWN = "FAILED_TEARDOWN"


class ItemState(StrEnum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETE = "COMPLETE"
    FAILED = "FAILED"
    SKIPPED_VERIFIED = "SKIPPED_VERIFIED"

